# Note: paths not being used atm
data_path: 'data/processed/joined_data.csv'
model_save_path: './models/'
result_save_path: './results/'

preprocessing:
  type: 'tfidf'
  ngram_min: 2
  ngram_max: 2

output:
  num_words: 500
  print: False

